# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  # BOX SETTINGS
  config.vm.box = "bento/ubuntu-18.04"

  # Install puppet agent
  config.vm.provision "shell", inline: <<-SHELL
    wget https://apt.puppetlabs.com/puppet5-release-$(lsb_release -cs).deb
    dpkg -i puppet5-release-$(lsb_release -cs).deb
    apt-get -qq update
    apt-get install -y puppet-agent
SHELL

    # PROVISION SETTINGS
    config.vm.provision "puppet" do |puppet|
        puppet.manifests_path = "./environments/test/manifests"
        puppet.options = "--verbose --debug"
    end
end
